### ISSUE TITLE
url不可以存在端口吗

### ISSUE THREAD

**Issue by inhopewerise** [BoyChai/Go-YuJian#3]

**Comment by Synex93** [comment]
已修复 https://github.com/BoyChai/Go-YuJian/commit/736defdbdf2b07fc2f6930bf5e3704474129de7d 编译好的客户端将更新到tag中

**Comment by Synex93** [comment]
已发布 可以查看tag https://github.com/BoyChai/Go-YuJian/releases/tag/v0.0.1-rc 的 Go-YuJian_v0.0.1-rc-2_win11_amd64.zip
